###
POST http://localhost:8080/api/process
Content-Type: application/json

{
  "name": "Seasons",
  "stages": [
    {
      "choiceText": [
        {"choice":"Spring"},
        {"choice":"Summer"},
        {"choice":"Fall"},
        {"choice":"Winter"}
      ],
      "stage_type": 2,
      "stageOrder": 1,
      "question": "What season is your favorite?"
    }
  ]
}

###
GET http://localhost:8080/api/process
Content-Type: application/json

###
GET http://localhost:8080/api/process/oneProcess?id=2
Content-Type: application/json
