POST http://localhost:8080/api/stage
Content-Type: application/json

{
  "processId": "2",
  "choiceText": [
    "food",
    "drinks",
    "utensils"
  ],
  "stage_type": 1,
  "stageOrder": 3,
  "question": "What are you bringing?"
}

###
GET http://localhost:8080/api/stage?processId=2
Content-Type: application/json

###
PUT http://localhost:8080/api/stage
Content-Type: application/json

{
  "id": "11",
  "choiceText": [
    "Outside",
    "drinks",
    "utensils"
  ],
  "stage_type": 2,
  "stageOrder": 4,
  "question": "Words?"
}