POST http://localhost:8080/api/stage
Content-Type: application/json

{
  "processId": "2",
  "multipleChoice": [
    "Dessert",
    "Appetizer",
    "Hot-dish"
  ],
  "stage_type": 1,
  "stageOrder": 3,
  "question": "What kind of food will you bring?"
}

###
GET http://localhost:8080/api/stage?processId=2
Content-Type: application/json

###
PUT http://localhost:8080/api/stage
Content-Type: application/json

{
  "id": "6",
  "multipleChoice": ["family","friends","people"]
}